version: '3.5'

services:
  app:
    build:
      context: ./
      args:
        BASE_PATH: /coursedata/
    image: coursedata_dev
    volumes:
      - ./:/usr/src/app
    ports:
      - 8000:8000
    environment:
      - MANKELI_TOKEN=DEVTOKEN
      - MANKELI_URL=http://localhost:9090
    container_name: coursedata_dev
